### ISSUE TITLE
Open on primary screen

### ISSUE THREAD

**Issue by philippludwig** [YggdrasiI/NeoLayoutViewer#10] opened 2019-09-05 16:56 UTC
It would be really nice if the layout viewer could open on the primary screen instead of the rightmost; at the moment, it always opens on my TV and since it is not possible to move the window via a hotkey, I have to turn on the TV whenever I start the layout viewer just to move the window.

**Comment by YggdrasiI** [comment] 2019-09-07 07:07
Hello phillippludwig,

which window manager does you use?

**Comment by philippludwig** [comment] 2019-09-08 09:27
I am using Cinnamon. -------- Ursprüngliche Nachricht --------Betreff: Re: [YggdrasiI/NeoLayoutViewer] Open on primary screen (#10)Von: "Olaf S." An: YggdrasiI/NeoLayoutViewer Cc: Philipp Ludwig ,Author Hello phillippludwig,
which window manager does you use?

**Comment by YggdrasiI** [comment] 2019-11-12 15:21
The issue is fixed in commit c7d3cb0 

I've added a new keyboard binding, 'monitor_shortcut' (<Ctrl><Alt><Shift>n), which allows a cycling trough the monitors. It is also possible to use the same value as 'show_shortcut'.

Remove $HOME/.config/neo_layout_viewer.conf to force the re-creation of the file.

**Closed by YggdrasiI** 2019-11-12 15:21 UTC

**Comment by philippludwig** [comment] 2019-11-19 18:31
Thanks!
