### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by nano13** [YggdrasiI/NeoLayoutViewer#3] opened 2017-12-23 00:05 UTC
make: *** No rule to make target 'src/version.vala', needed by 'bin/neo_layout_viewer'.  Stop.
version.vala is blacklisted in the .gitignore

**Comment by YggdrasiI** [comment] 2017-12-23 14:57
Hello Nano13,

thanks for this information. Please build a Makefile target manually:
`make gen_version`
`make`

The next update should resolve this dependency error, too.

Regards Yggdrasil

**Comment by YggdrasiI** [comment] 2017-12-23 20:43
Fixed in commit 8e165fb

**Comment by nano13** [comment] 2017-12-24 05:17
Thank you!
Sadly now i have another issue with this fix:

version.vala:1.27-1.27: error: syntax error, unexpected character
namespace NeoLayoutViewer{\n public

If i deleteall the $(NL) from the makefile (lines 145-150), then it compiles correctly.

**Comment by YggdrasiI** [comment] 2017-12-24 09:31
Which OS and Make version (make -v) does you use?

Background:
The error is caused by a missing backslash interpretation of the echo command. Normally, echo suppress the conversion without the '-e' flag, but make seems to convert newline characters itself  (or add -e to echo commands). That was probably a wrong assumption.

**Comment by YggdrasiI** [comment] 2017-12-24 09:50
I convert the critical calls of the built-in 'echo' command by /bin/echo.
This should normalize the output.

**Closed by YggdrasiI** 2017-12-24 09:50 UTC

**Comment by nano13** [comment] 2017-12-24 11:39
Thanks, making works now!
My OS is arch linux, make-version (GNU Make) 4.2.1
